### ISSUE TITLE
coordinates

### ISSUE THREAD

**Issue by AndreyDiDev** [guy881/IrisDetector#2]
How can I get the x,y coordinates of the pupils?

**Comment by tugaybozik** [comment]
That is a good question. How can I find pupils’ pixel coordinates?

**Comment by guy881** [comment]
`EyerisDetector` class has a list of coordinates of found pupils called `irises`. ;)

**Comment by andin2** [comment]
Also if the coordinates are appended to an array named irises, how can I index the second to last appended row of values? Would you happen to know?
